server:
  port: 8080

spring:
  profiles:
    active: dev
  application:
    name: UReport
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ureport?serverTimezone=GMT%2B8&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false
    username: root
    password: Root123456
#  redis:
#    host: 127.0.0.1
#    port: 6379
#    database: 0
#    timeout: 3000ms
#    lettuce:
#      pool:
#        max-active: 20
#        max-wait: -1
#        max-idle: 8
#        min-idle: 0
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/hy/ureport/mapper/xml/*.xml